Send SIGHUP to controller jujud process when configuration file changes
juju/juju-controller pull request #60
Opened 2024-01-25 16:13 UTC by manadart

This patch does two things:
- We no longer assume that the identity of the controller itself is congruent with the controller unit ID. We now get this information from the running controller jujud process.
- When the controller configuration file is changed, we send a SIGHUP to the controller's process, which will be detected there, causing a reload of the new configuration.

2024-02-02 15:53 UTC, SimonRichardson requested changes

2024-02-02 15:53 UTC, SimonRichardson commented on src/charm.py
> +            ['systemctl', 'list-units', 'jujud-machine-*.service', '--no-legend'], text=True)
You can't do this on k8s.

2024-02-06 14:38 UTC, manadart commented on src/charm.py
> +            ['systemctl', 'list-units', 'jujud-machine-*.service', '--no-legend'], text=True)
Doing everything with `pgrep -af` now.

2024-03-05 11:50 UTC, manadart commented
Superseded by #68.

2024-03-05 11:50 UTC, closed without merging